name: Automação Download TUSS ANS

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests urllib3

      - name: Executar script de download
        run: python download_ans.py

      - name: Salvar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: TUSS-ANS-Planilha
          path: downloads/
          retention-days: 30
