name: Automação Download TUSS ANS

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

# Dá permissão para o bot salvar arquivos no repositório
permissions:
  contents: write

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests urllib3

      - name: Executar script de download
        run: python download_ans.py

      - name: Salvar/Commitar alterações no GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add downloads/TUSS_ANS.xlsx
          git commit -m "Atualiza planilha TUSS ANS [skip ci]" || echo "Sem mudanças para salvar"
          git push
