name: Automação Download TUSS ANS

on:
  schedule:
    # Executa toda segunda-feira às 08:00 (Horário de Brasília) / 11:00 UTC
    - cron: '0 11 * * 1'
  workflow_dispatch: # Permite que você clique em um botão para rodar manualmente se quiser

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4.1.7

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5.1.1

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script de download
        run: python download_ans.py

      - name: Salvar o arquivo baixado como Artefato
        uses: actions/upload-artifact@v4.3.4
        with:
          name: TUSS-ANS-Planilha
          path: downloads/
          retention-days: 30
